export const SESSION_EVENT_TYPES = Object.freeze([
  "session:start",
  "session:resume",
  "session:branch_created",
  "session:branch_activated",
  "session:rewind_preview",
  "session:rewind_started",
  "session:rewind_applied",
  "session:rewind_conflict",
  "session:rewind_failed",
  "session:rewind_restore_started",
  "session:rewind_restored",
  "session:rewind_recovery_failed",
  "recovery:started",
  "recovery:blocked",
  "recovery:report",
  "tx:opened",
  "tx:committed",
  "tx:recovered",
  "turn:paused",
  "turn:rehydrated",
  "turn:resumed",
  "turn:cancelled",
  "takeover:requested",
  "takeover:completed",
  "user:message",
  "agent:turn_started",
  "agent:step",
  "model:request",
  "model:response",
  "tool:call",
  "tool:result",
  "permission:decision",
  "approval:requested",
  "approval:resolved",
  "context:snapshot",
  "context:pin",
  "context:unpin",
  "context:warm",
  "context:cache_loaded",
  "context:cache_saved",
  "context:cache_reused",
  "context:semantic_degraded",
  "file:diff_preview",
  "file:diff_applied",
  "file:rollback_applied",
  "file:transaction_started",
  "file:transaction_committed",
  "file:transaction_failed",
  "file:transaction_rolled_back",
  "file:rollback_conflict",
  "verification:result",
  "repair:started",
  "repair:attempt",
  "repair:result",
  "repair:exhausted",
  "orchestration:planned",
  "orchestration:round_started",
  "orchestration:replanned",
  "orchestration:subtask_started",
  "orchestration:subtask_reviewed",
  "orchestration:completed",
  "orchestration:routed",
  "agent:final",
  "agent:error",
  // 跨任务经验记忆(C4)事件族:v1.9.0 M1 登记闭环——四类此前有生产者却未登记
  // (schema/回放守卫发现)。生产者:orchestrator.js:28/:123、index.js:245/:453。
  "experience:retrieved",
  "experience:consolidated",
  "experience:pending_approval",
  "experience:pending_resolved"
]);

export function isSessionEventType(type) {
  return SESSION_EVENT_TYPES.includes(type);
}

export function assertSessionEventType(type) {
  if (!isSessionEventType(type)) {
    throw new Error(`unknown session event type: ${type}`);
  }
}
